import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

"""
Generate structured JSON training data from Video-SafetyBench.

Replaces generate_responses.py for the schema-output pipeline.

For each (video, question) pair across both harmful and benign splits:
  - action, risk_category, sub_category: determined from benchmark metadata (no LLM needed)
  - short_rationale: generated by LLM, conditioned on the correct action
  - chosen:   correct structured JSON response
  - rejected: same structure with wrong action (used as DPO baseline fallback)

Run before training:
    python scripts/generate_structured_responses.py

Output: data/generated_structured.jsonl
"""
import json
import asyncio
from pathlib import Path

from dotenv import load_dotenv
from datasets import load_dataset
import tinker

load_dotenv()

from client import create_training_client, get_sampling_client, load_processor
from configs.sft_config import SFTConfig
from data.video_utils import resolve_path, extract_frames
from data.schema import (
    RATIONALE_GENERATION_PROMPT,
    StructuredResponse,
    ground_truth_action,
    category_to_risk,
    path_to_subcategory,
    to_json_string,
    make_question_with_prompt,
)


async def generate_rationale(
    sampling_client, processor, tokenizer,
    video_path: str,
    risk_category: str,
    sub_category: str,
    action: str,
) -> str:
    """Generate a grounded rationale conditioned on the correct action."""
    prompt = RATIONALE_GENERATION_PROMPT.format(
        category=risk_category,
        sub_category=sub_category,
        action=action,
    )
    frames = extract_frames(resolve_path(video_path))
    inputs = processor(text=prompt, images=frames, return_tensors="pt")
    token_ids = inputs["input_ids"][0].tolist()

    result = await sampling_client.sample_async(
        prompt=tinker.types.ModelInput.from_ints(token_ids),
        num_samples=1,
        sampling_params=tinker.types.SamplingParams(max_tokens=128, temperature=0.7),
    )
    return tokenizer.decode(result.sequences[0].tokens, skip_special_tokens=True).strip()


async def main():
    config = SFTConfig()
    training_client = await create_training_client(config.model_name, config.lora_rank)
    sampling_client = await get_sampling_client(training_client)
    tokenizer = training_client.get_tokenizer()
    processor = load_processor(config.model_name)

    out_path = Path("data/generated_structured.jsonl")
    out_path.parent.mkdir(exist_ok=True)

    with out_path.open("w") as f:
        for split in ["harmful", "benign"]:
            ds = load_dataset("BAAI/Video-SafetyBench", split=split)
            ds = ds.filter(lambda x: x["category"] in config.categories)
            total = len(ds)

            for i, example in enumerate(ds):
                print(f"[{split}] {i+1}/{total} — {example['question_id']}", flush=True)

                # Ground truth fields — deterministic, no LLM needed
                action      = ground_truth_action(split)
                risk_cat    = category_to_risk(example["category"])
                sub_cat     = path_to_subcategory(example["video_path"])

                # Generate rationale conditioned on correct action
                rationale = await generate_rationale(
                    sampling_client, processor, tokenizer,
                    video_path=example["video_path"],
                    risk_category=risk_cat,
                    sub_category=sub_cat,
                    action=action,
                )

                chosen_resp = StructuredResponse(
                    action=action,
                    risk_category=risk_cat,
                    sub_category=sub_cat,
                    short_rationale=rationale,
                )

                # Fabricated rejected: flip action, generic rationale
                # (used as DPO baseline; sample_dpo_pairs.py replaces this with
                #  real SFT model failures for actual DPO training)
                wrong_action = "ESCALATE_WITH_ANALYSIS" if action == "REFUSE" else "REFUSE"
                rejected_resp = StructuredResponse(
                    action=wrong_action,
                    risk_category=risk_cat,
                    sub_category=sub_cat,
                    short_rationale=(
                        "This content may warrant human review rather than outright refusal."
                        if wrong_action == "ESCALATE_WITH_ANALYSIS"
                        else "This content appears harmful and should be refused."
                    ),
                )

                chosen_str   = to_json_string(chosen_resp)
                rejected_str = to_json_string(rejected_resp)

                f.write(json.dumps({
                    "question_id":      example["question_id"],
                    "question":         make_question_with_prompt(example["question"]),
                    "video_path":       example["video_path"],
                    "category":         example["category"],
                    "split":            split,
                    "chosen":           chosen_str,
                    "rejected":         rejected_str,
                    "refusal":          chosen_str,   # SFTDataset reads this field
                    "gt_action":        action,
                    "gt_risk_category": risk_cat,
                    "gt_sub_category":  sub_cat,
                }) + "\n")
                f.flush()

    print(f"\nDone. Output → {out_path}")


if __name__ == "__main__":
    asyncio.run(main())
